package Views;

import Controllers.VehicleController;

public class VehiclePanel extends javax.swing.JPanel {
    private VehicleController controller;

    /**
     * Creates new form VehiclePanel
     */
    public VehiclePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        controller = new VehicleController();
        tablePane = new javax.swing.JScrollPane();
        vehicleTable = new javax.swing.JTable();
        newRecordButton = new javax.swing.JButton();
        updateRecordButton = new javax.swing.JButton();
        deleteRecordButton = new javax.swing.JButton();

        vehicleTable.setModel(new javax.swing.table.DefaultTableModel(
            controller.getVehicleTableData(),
            new String [] {
                "VehicleID", "Plate Number", "Fuel Economy (cost/km)", "Last Maintenance Date", "Max Load Weight (kg)", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vehicleTable.getTableHeader().setReorderingAllowed(false);
        tablePane.setViewportView(vehicleTable);

        newRecordButton.setText("New Record");
        newRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRecordButtonDriverTableActions(evt);
            }
        });

        updateRecordButton.setText("Update Record");
        updateRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRecordButtonActionPerformed(evt);
            }
        });

        deleteRecordButton.setText("Delete Record");
        deleteRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRecordButtonDriverTableActions(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(newRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                        .addComponent(updateRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tablePane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(tablePane, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteRecordButton)
                    .addComponent(updateRecordButton)
                    .addComponent(newRecordButton))
                .addContainerGap())
        );
    }// </editor-fold>                        

    public void refresh() {
        removeAll();
        initComponents();
        revalidate();
        repaint();
    }

    private void newRecordButtonDriverTableActions(java.awt.event.ActionEvent evt) {                                                   
        NewVehicleForm dialog = new NewVehicleForm(new javax.swing.JFrame(), true);
        dialog.setParentPanel(this);
        dialog.setVisible(true);
    }                                                  

    private void updateRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        int selectedRow = vehicleTable.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(
                this, 
                "Please select a record to update.", 
                "No Selection", 
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        UpdateVehicleForm dialog = new UpdateVehicleForm(new javax.swing.JFrame(), true);
        dialog.setParentPanel(this);
        dialog.setFields(
            (int) vehicleTable.getValueAt(selectedRow, 0), // vehicleID
            (String) vehicleTable.getValueAt(selectedRow, 1), // plate number
            String.valueOf(vehicleTable.getValueAt(selectedRow, 2)), // fuel economy
            vehicleTable.getValueAt(selectedRow, 3) != null ? vehicleTable.getValueAt(selectedRow, 3).toString() : "", // last maintenance date converted to String
            String.valueOf(vehicleTable.getValueAt(selectedRow, 4)) // max load weight
        );
        dialog.setVisible(true);
    }                                                  

    private void deleteRecordButtonDriverTableActions(java.awt.event.ActionEvent evt) {                                                      
        controller.deleteRecord((int)vehicleTable.getValueAt(vehicleTable.getSelectedRow(), 0));
        refresh();
    }                                                     

    // Variables declaration - do not modify                     
    private javax.swing.JButton deleteRecordButton;
    private javax.swing.JButton newRecordButton;
    private javax.swing.JScrollPane tablePane;
    private javax.swing.JButton updateRecordButton;
    private javax.swing.JTable vehicleTable;
    // End of variables declaration                   
}
